### ISSUE TITLE
lezen van "all cards.txt"

### ISSUE THREAD

**Issue by MT-Arnoldussen** [MT-Arnoldussen/JavaStone#4]
wss handig om om te zetten naar List<Map<String, String>>, zodat de waardes in die list dan makkelijk tot hero/minion/weapon/spell om kunnen worden gezet wanneer die classes klaar zijn

**Comment by hipstertwix** [comment]
[{        "image_url"= "http,         "id"= 7,,         "set"= "basic",,         "type"= "hero",,         "attack"= null,,         "description"= "",,         "race"= null,,         "collectible"= true,,
